### ISSUE TITLE
Enhancements for Future Release tracking

### ISSUE THREAD

**Issue by miketheman** [sous-chefs/nginx#397]
# What is this?

This issue is meant to help track the open issues that should be resolved before cutting the 3.0.0 release.
It is not exhaustive by any means, but attempts to cover the issues.

It will be updated (edited) as needed, so as to reflect the remaining efforts involved. Comments/other issues will be linked as necessary to this main section.

Release-time test matrix:
- Chef 12-latest
- Ubuntu 14.04, 16.04
- CentOS 6, 7
## Must have for release
- [x] Support for systemd (#384)
- [ ] Sort out pidfie location issues (#292, #377)
- [ ] Allow control of base config's `error_log/access_log` location (#388)
- [ ] Platform-specific spec coverage for all resource actions
- [ ] Address any open TODOs (run `rake notes` to find)
- [ ] README updated with examples and use cases
- [ ] Mailing list announcement
- [ ] Supermarket release
## Nice to have
- [ ] Update upstart template & base config to not need to daemon/expect spawn
- [ ] Support a notion of `nginx_site 'mysite' { action :enable|disable }` to control symlinks
- [ ] Fully docker-supported build/test cycle (so as to support testing via CircleCI)
- [ ] Close out any pre-3.0 issues with `wontfix`

**Comment by miguelaferreira** [comment]
I would be happy to finish #384, but I do need some pointers on what still needs to be done.

**Comment by miketheman** [comment]
@miguelaferreira Awesome! I've been focusing on getting a workable CI going, so I need to finish up a few changes I made yesterday to get a clean run.
Once that's on the mainline branch, can you rebase & test? This will get the most recent setup of testing/CI.

**Comment by miguelaferreira** [comment]
Sure. Please ping me when you're ready and I'll rebase and test.

**Comment by miketheman** [comment]
Updated to remove Chef 11 from the support list.

**Comment by wk8** [comment]
Hey guys,

Just a small question: when do you think the 3.0 version of this cookbook will be available? Got a legacy Chef set up that I'm bringing up to date that still uses v 1.8 of this cookbook, but if 3.0 comes out soonish I'd rather wait for it instead of upgrading to 2.7.

Thanks!

**Comment by iennae** [comment]
@miketheman any chance you can release @tas50 PR #422 so that we have a working 2.X branch that resolves a lot of folks problems?

Thanks for taking the time to look at this.

**Comment by eherot** [comment]
@miketheman do you want/need help maintaining and administrating this cookbook? This is a hugely important cookbook for a lot of people's environments and it basically hasn't been touched (including merging relatively simple but essential pull requests) since July...

**Comment by tas50** [comment]
@eherot Check out https://github.com/chef-cookbooks/chef_nginx

**Comment by miketheman** [comment]
@eherot I'd gladly accept help on completing the list as mentioned above.

**Comment by damacus** [comment]
Closing due to inactivity. 

If this is still an issue please reopen or open another issue. Alternatively drop by the #sous-chefs channel on the [Chef Community Slack](http://community-slack.chef.io/) and we'll be happy to help! 

Thanks,
Sous-Chefs
